services:

  #image used
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306

      #WORDPRESS_DB_USER: exampleuser #from wordpress guide
      WORDPRESS_DB_USER: wordpress

      #WORDPRESS_DB_PASSWORD: examplepass #from wordpress guide
      #WORDPRESS_DB_NAME: exampledb #from wordpress guide

      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db
    secrets:
      - db_password

  #MySQL database storing
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: wordpress #from secrets documentation

      #MYSQL_USER: exampleuser
      MYSQL_USER: wordpress #from secrets documentation

      #MYSQL_PASSWORD: examplepass #from wordpress guide
      #MYSQL_RANDOM_ROOT_PASSWORD: '1' #from wordpress guide

      MYSQL_PASSWORD_FILE: /run/secrets/db_password #sends password to password file for secrets

    volumes:
      - db_data:/var/lib/mysql/data #persistent data
    secrets:
      - db_root_password 
      - db_password

  # Web Application Service from L31 Participation
  web:
    image: smartonfhir/patient-browser:latest # access with ext ip:3000
    ports:
      - "80" # Expose the application port
    environment:
      - DATABASE_URL=mysql://wordpress:db_password@db:3306/wordpress # Connect to the database
    depends_on:
      - db # Start the database before the application
    restart: always
    deploy: 
      mode: replicated
      replicas: 2
      endpoint_mode: vip
      resources:
        limits:
          cpus: '0.50' # Limits cpu resource as number of cores containers can use
          memory: 50M # Limits memory usage to 50MB
        reservations:
          cpus: '0.25' # cpu resource reserved for container

#secrets for password encryption
secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt

volumes:
  wordpress:
  db_data:

#links used:
#wordpress guide: https://hub.docker.com/_/wordpress 
#wordpress secrets: https://docs.docker.com/compose/how-tos/use-secrets/
